version: "3.9"
services:
  aprsc:
    image: hemna6969/trackdirect-aprsc:latest
    build:
      context: .
      dockerfile: aprsc.dockerfile
    ports:
      - "10152:10152"
      - "14580:14580"
      - "10155:10155"
      - "14501:14501"
    volumes:
      - $PWD/config/aprsc.conf:/opt/aprsc/etc/aprsc.conf

  collector:
    image: hemna6969/trackdirect-python:latest
    build:
      context: .
      dockerfile: trackdirect-python.dockerfile
    volumes:
      - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/collector.sh trackdirect.ini 0
    depends_on:
      - "db"
      - "aprsc"

  cron:
    image: hemna6969/trackdirect-cron:latest
    build:
      context: .
      dockerfile: trackdirect-python-cron.dockerfile
    volumes:
      - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/cron.sh trackdirect.ini 0
    depends_on:
      - "collector"

  websocket:
    image: hemna6969/trackdirect-python:latest
    build:
      context: .
      dockerfile: trackdirect-python.dockerfile
    volumes:
      - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/wsserver.sh trackdirect.ini
    ports:
      - "9001:9001"
    depends_on:
      - "db"
      - "aprsc"

  web:
    image: hemna6969/trackdirect-web:latest
    build:
      context: .
      dockerfile: trackdirect-apache.dockerfile
    volumes:
      - $PWD/config/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
      - $PWD/heatmaps:/root/trackdirect/htdocs/public/heatmaps
    ports:
      - "80:80"
    depends_on:
      - "db"

  db:
    image: hemna6969/trackdirect-db:latest
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: trackdirect
    volumes:
      - $PWD/db:/var/lib/postgresql/data
